// <auto-generated />
using Blood4A.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blood4A.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Blood4A.Models.AberturaFechamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dia_Da_Semana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario_Abertura")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Horario_Fechamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("referente_a")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("referente_a");

                    b.ToTable("AberturaFechamento");
                });

            modelBuilder.Entity("Blood4A.Models.Agentes", b =>
                {
                    b.Property<int>("Id_Agente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj_Agente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email_Agente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_Agente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha_Agente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Agente");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("Blood4A.Models.Clinicas", b =>
                {
                    b.Property<int>("Id_Clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cnpj_Clinica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_Clinica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cep_location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Clinica");

                    b.HasIndex("cep_location");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("Blood4A.Models.Doacoes", b =>
                {
                    b.Property<int>("Id_Doacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data_Doacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hora_Doacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_agente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_clinica")
                        .HasColumnType("INTEGER");

                    b.Property<int>("id_doador")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Doacao");

                    b.HasIndex("id_agente");

                    b.HasIndex("id_clinica");

                    b.HasIndex("id_doador");

                    b.ToTable("Doacoes");
                });

            modelBuilder.Entity("Blood4A.Models.Doadores", b =>
                {
                    b.Property<int>("Id_Doador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf_Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Data_Nascimento_Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome_Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone_Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_Sanguineo_Doador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cep_location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("id_escolaridade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Doador");

                    b.HasIndex("cep_location");

                    b.HasIndex("id_escolaridade");

                    b.ToTable("Doadores");
                });

            modelBuilder.Entity("Blood4A.Models.Escolaridade", b =>
                {
                    b.Property<int>("Id_Escolaridade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao_Escolaridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grau_Escolaridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Escolaridade");

                    b.ToTable("Escolaridade");
                });

            modelBuilder.Entity("Blood4A.Models.Localizacoes", b =>
                {
                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Uf")
                        .HasColumnType("INTEGER");

                    b.HasKey("Cep");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("Blood4A.Models.AberturaFechamento", b =>
                {
                    b.HasOne("Blood4A.Models.Clinicas", "obj_referente_a")
                        .WithMany()
                        .HasForeignKey("referente_a")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("obj_referente_a");
                });

            modelBuilder.Entity("Blood4A.Models.Clinicas", b =>
                {
                    b.HasOne("Blood4A.Models.Localizacoes", "obj_cep_location")
                        .WithMany()
                        .HasForeignKey("cep_location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("obj_cep_location");
                });

            modelBuilder.Entity("Blood4A.Models.Doacoes", b =>
                {
                    b.HasOne("Blood4A.Models.Agentes", "obj_id_agente")
                        .WithMany()
                        .HasForeignKey("id_agente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood4A.Models.Clinicas", "obj_id_clinica")
                        .WithMany()
                        .HasForeignKey("id_clinica")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood4A.Models.Doadores", "obj_id_doador")
                        .WithMany()
                        .HasForeignKey("id_doador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("obj_id_agente");

                    b.Navigation("obj_id_clinica");

                    b.Navigation("obj_id_doador");
                });

            modelBuilder.Entity("Blood4A.Models.Doadores", b =>
                {
                    b.HasOne("Blood4A.Models.Localizacoes", "obj_cep_location")
                        .WithMany()
                        .HasForeignKey("cep_location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blood4A.Models.Escolaridade", "obj_id_escolaridade")
                        .WithMany()
                        .HasForeignKey("id_escolaridade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("obj_cep_location");

                    b.Navigation("obj_id_escolaridade");
                });
#pragma warning restore 612, 618
        }
    }
}
